name: Daily Fudan

on:
  schedule:
    - cron:  "0 22 * * *"
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
  
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install easyocr pillow numpy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-300 -n 1)
        
      - name: Run sign
        run: STD_ID=${{ secrets.STD_ID }} PASSWORD=${{ secrets.PASSWORD }} python3 main.py
